version: '3.8'

services:
  java:
    build: .
    environment:
      - DISCODING_DB_HOST=db:3306
      - DISCODING_DB_NAME=discoding
      - DISCODING_DB_USER=discoding
      - DISCODING_DB_PASSWORD=discoding
    depends_on:
      - db
    ports:
      - '8080:8080'